modules:
	sed -i 's/EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE/#EXTRA_CFLAGS# += -DCONFIG_CONCURRENT_MODE/g' git/Makefile
	$(MAKE) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(shell pwd)/git KSRC=$(KERNEL_SRC) modules

install:
	$(MAKE) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(shell pwd)/git INSTALL_MOD_PATH=$(shell pwd)/package install

modules_install:
	@echo TRY INSTALL

.PHONY: modules clean

clean:
	$(MAKE) -C git/ clean
